'use strict';
const assert=require('assert');
const fs=require('fs');
const v182=fs.readFileSync(require.resolve('../apps-script/PolicySyncV182.gs'),'utf8');
assert.ok(v182.includes("SCRIPT_VERSION: 'crew-apps-script-v1.8.2'"));
assert.ok(v182.includes('TRIGGER_MINUTES: 10'));
assert.ok(v182.includes("newTrigger('refreshCrewNewsV182')"));
assert.ok(v182.includes('.everyMinutes(CREW_POLICY_SYNC_V182.TRIGGER_MINUTES)'));
assert.ok(v182.includes('refreshCrewNewsV181();'));
console.log('Apps Script v1.8.2 10-minute policy regression: ok');
